"""add audit_event hash chain

Revision ID: 81b311712d89
Revises: b0aaf065eb08
Create Date: 2026-08-24 21:37:39.976369

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81b311712d89'
down_revision = 'b0aaf065eb08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The two UNIQUE constraints below are load-bearing, not hygiene:
    # ix_audit_event_seq (unique) and UniqueConstraint('hash') are what stop
    # the chain forking if the advisory lock in audit.record() is ever
    # bypassed -- a second writer claiming an already-taken position fails
    # its insert instead of silently creating two valid-looking branches.
    #
    # No foreign key on actor_id, deliberately -- see the AuditEvent
    # docstring in db/models.py: an audit log has to outlive its subject,
    # and a FK would either block deleting a user or cascade away exactly
    # the evidence that the deletion happened.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prev_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_actor_id'), 'audit_event', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_event_created_at'), 'audit_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_event_seq'), 'audit_event', ['seq'], unique=True)
    op.create_index(op.f('ix_audit_event_target_id'), 'audit_event', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_event_target_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_seq'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_created_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
