"""add users and per-user isolation

Revision ID: ea37ad306457
Revises: eb3e965b3e6a
Create Date: 2026-08-24 11:43:38.965953

Adds the app_user table and makes task/memoryentry/googleconnection
per-user. task.owner_id, memoryentry.owner_id, and googleconnection.user_id
are added NOT NULL with no backfill path -- there is no sensible owner to
assign to rows created before auth existed. Apply this only against a fresh
database (a local dev DB: `docker compose down -v && docker compose up`);
against a database with existing task/memoryentry/googleconnection rows this
migration will fail at the ADD COLUMN ... NOT NULL step, by design, rather
than silently dropping or misattributing that data.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ea37ad306457'
down_revision = 'eb3e965b3e6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_google_sub'), 'app_user', ['google_sub'], unique=True)
    op.add_column('escalation', sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='plan'))
    op.add_column('googleconnection', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_googleconnection_user_id'), 'googleconnection', ['user_id'], unique=True)
    op.create_foreign_key('fk_googleconnection_user_id_app_user', 'googleconnection', 'app_user', ['user_id'], ['id'])
    op.add_column('memoryentry', sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_memoryentry_owner_id'), 'memoryentry', ['owner_id'], unique=False)
    op.create_foreign_key('fk_memoryentry_owner_id_app_user', 'memoryentry', 'app_user', ['owner_id'], ['id'])
    op.add_column('task', sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('task', sa.Column('is_eval', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_task_owner_id'), 'task', ['owner_id'], unique=False)
    op.create_foreign_key('fk_task_owner_id_app_user', 'task', 'app_user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_task_owner_id_app_user', 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_owner_id'), table_name='task')
    op.drop_column('task', 'is_eval')
    op.drop_column('task', 'owner_id')
    op.drop_constraint('fk_memoryentry_owner_id_app_user', 'memoryentry', type_='foreignkey')
    op.drop_index(op.f('ix_memoryentry_owner_id'), table_name='memoryentry')
    op.drop_column('memoryentry', 'owner_id')
    op.drop_constraint('fk_googleconnection_user_id_app_user', 'googleconnection', type_='foreignkey')
    op.drop_index(op.f('ix_googleconnection_user_id'), table_name='googleconnection')
    op.drop_column('googleconnection', 'user_id')
    op.drop_column('escalation', 'kind')
    op.drop_index(op.f('ix_app_user_google_sub'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
